return {
	require('viktor.lsp.clangd'),
	require('viktor.lsp.bufls'),
	require('viktor.lsp.cmake'),
	require('viktor.lsp.custom-elements-languageserver'),
	require('viktor.lsp.eslint'),
	require('viktor.lsp.gopls'),
	require('viktor.lsp.lua_ls'),
	require('viktor.lsp.neodev'),
	require('viktor.lsp.rust'),
	require('viktor.lsp.python'),
	require('viktor.lsp.tailwindcss'),
	require('viktor.lsp.toml'),
	require('viktor.lsp.tsserver'),
}
